### PR TITLE
fix: Update recipe for v0.4.0

### PR DESCRIPTION
**Pull request by setu4993**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by setu4993** [comment]
@conda-forge-admin, please rerender

**Comment by setu4993** [comment]
@conda-forge-admin, please rerender

**Comment by setu4993** [comment]
Everything except `pypy` is building fine. Seeing the error for PyPy, which I have no idea how to fix:

```sh
 🍹 Building a mixed python/rust project
  🔗 Found pyo3 bindings
  🐍 Using host PyPy 3.9 at /home/conda/feedstock_root/build_artifacts/safetensors_1707287575371/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python for cross-compiling preparation
  💥 maturin failed
    Caused by: Could not find _sysconfigdata*.py in /home/conda/feedstock_root/build_artifacts/safetensors_1707287575371/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.9/site-packages/../
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-4sh4b7df', '--interpreter', '/home/conda/feedstock_root/build_artifacts/safetensors_1707287575371/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
```

Any help would be appreciated here @xhochy, @h-vetinari. Tagging you'll since I saw a few other feedstocks where you had contributed to fixes for PyPy (https://github.com/conda-forge/pydantic-core-feedstock/pull/38, https://github.com/conda-forge/bcrypt-feedstock/pull/25, https://github.com/conda-forge/cryptography-feedstock/pull/111).

This feedstock has been outdated for a few months and is blocking https://github.com/conda-forge/transformers-feedstock/pull/145 now so I want to get this updated.

**Comment by h-vetinari** [comment]
> Any help would be appreciated here @xhochy, @h-vetinari.

I raised an [issue](https://github.com/conda-forge/pypy3.6-feedstock/issues/117) for you on the pypy-feedstock. In the meantime, my suggestion is to add
```
# due to https://github.com/conda-forge/pypy3.6-feedstock/issues/117
skip: True  # [(aarch64 or ppc64le) and python_impl == "pypy"]
```
for now and not let yourself be blocked by this. Once the pypy issue gets resolved, you can remove the skip again.

**Comment by jan-janssen** [comment]
> > Any help would be appreciated here @xhochy, @h-vetinari.
> 
> I raised an [issue](https://github.com/conda-forge/pypy3.6-feedstock/issues/117) for you on the pypy-feedstock. In the meantime, my suggestion is to add
> 
> ```
> # due to https://github.com/conda-forge/pypy3.6-feedstock/issues/117
> skip: True  # [(aarch64 or ppc64le) and python_impl == "pypy"]
> ```
> 
> for now and not let yourself be blocked by this. Once the pypy issue gets resolved, you can remove the skip again.

I agree, that is most likely the best solution for the moment.

**Comment by xhochy** [comment]
Please wait, I have an idea!

**Review by jan-janssen — APPROVED** [review]
Looks good to me. Thanks @setu4993 and @xhochy

**Comment by setu4993** [comment]
Thank you for the help, @xhochy, @h-vetinari and @jan-janssen!

**Pull request merged**
